version: '3.9'

services:
  temperature-broker:
    image: eclipse-mosquitto:2
    container_name: temperature-broker
    command: >
      sh -c 'printf "listener 1883 0.0.0.0\nallow_anonymous true\npersistence false\n" >
      /mosquitto/config/mosquitto.conf && exec mosquitto -c /mosquitto/config/mosquitto.conf'
    networks:
      - factory-net
    ports:
      - "1883:1883"

  cloud-broker:
    image: eclipse-mosquitto:2
    container_name: cloud-broker
    command: >
      sh -c 'printf "listener 1883 0.0.0.0\nallow_anonymous true\npersistence false\n" >
      /mosquitto/config/mosquitto.conf && exec mosquitto -c /mosquitto/config/mosquitto.conf'
    networks:
      - factory-net
    ports:
      - "1884:1883"

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    networks:
      - factory-net
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    depends_on:
      - temperature-broker
      - cloud-broker

  sensor:
    build: ./sensor
    container_name: sensor
    networks:
      - factory-net
    depends_on:
      - temperature-broker

  cloud-listener:
    build: ./cloud
    container_name: cloud
    networks:
      - factory-net
    depends_on:
      - cloud-broker

networks:
  factory-net:
    name: factory-net
    driver: bridge

volumes:
  nodered_data:
